apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Release.Name }}-deployment
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{- .Release.Name | indent 1 }}-deployment
  template:
    metadata:
      labels:
        app: {{- .Release.Name | indent 1 }}-deployment
    spec:
      containers:
        - image: kodekloud/webapp-color
          name: webapp-color
          env:
            - name: APP_COLOR
              value: {{- .Values.app.color | indent 1 }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: {{ .Values.app.requests.cpu }}
              memory: {{ .Values.app.requests.memory }}
            limits:
              cpu: {{ .Values.app.limits.cpu }}
              memory: {{ .Values.app.limits.memory }}
